apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: snack-bar-payments-db-pvc
  namespace: snack-bar-payments
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: standard
